### ISSUE TITLE
Addsticker doesn't know how to break a long string

### ISSUE THREAD

**Issue by GabrielSimonetto** [caravelahc/pico-bot#17]
`NAAAAAAAAAAAAAAAAAAAAAAAAOOOOOOOOOOOOOO`

![Screenshot_20201011_205541](https://user-images.githubusercontent.com/42247511/95693719-24b24f00-0c04-11eb-86f0-7b8680826b2c.png)

I thought this could be a problem for regular phrases, but it seems fine enough

![Screenshot_20201011_210218](https://user-images.githubusercontent.com/42247511/95693866-1153b380-0c05-11eb-8b27-d9b5baf6b931.png)

**Comment by diogojs** [comment]
Now it does.
