### ISSUE TITLE
Add different colors for user names and avatars

### ISSUE THREAD

**Issue by diogojs** [caravelahc/pico-bot#20]
Telegram uses a bunch of different colors for user names and "avatar bubble".
Stickers should be created using these colors as well.

**Comment by JPTIZ** [comment]
But that color changes from chat to chat and for each user's client, right? How would we choose a color?

**Comment by diogojs** [comment]
My idea was to have a list with possible colors, and to pick a random one from this list when creating the sticker.
Just to add some variety to the stickers.
