### ISSUE TITLE
Error when user has no profile picture

### ISSUE THREAD

**Issue by diogojs** [caravelahc/pico-bot#6]
If msg's author has no profile picture, bot should create an avatar with its initial.

**Comment by alexandremj** [comment]
Located where the issue happens in the code (handlers.py:135, instead of generating the avatar currently just notifies an error on downloading the photo and aborts the operation)

Does anyone know what are the background color rules for the avatar on Telegram?

**Comment by diogojs** [comment]
Fixed at PR #19
